version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: safec_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: creditcard_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - safec_network

  # Backend API
  backend:
    build: .
    container_name: safec_backend
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/creditcard_db?authSource=admin
      - SECRET_KEY=your-super-secret-key-here
      - JWT_SECRET_KEY=your-jwt-secret-key-here
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - safec_network
    volumes:
      - ./uploads:/app/uploads

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: safec_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
    networks:
      - safec_network

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: safec_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - safec_network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  safec_network:
    driver: bridge